/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./website/templates/*"],
  safelist: [
    // Classes for tables (standings page)
    "w-full",
    "text-center",
    "border-t",
    "hover:bg-gray-100",
    "py-2",
    "text-left",

    // Classes for team cards (home page)
    "bg-mercedes",
    "bg-ferrari",
    "bg-red_bull",
    "bg-mclaren",
    "bg-aston_martin",
    "bg-alpine",
    "bg-alfa",
    "bg-haas",
    "bg-alphatauri",
    "bg-williams",
    "hover:text-mercedes",
    "hover:text-ferrari",
    "hover:text-red_bull",
    "hover:text-mclaren",
    "hover:text-aston_martin",
    "hover:text-alpine",
    "hover:text-alfa",
    "hover:text-haas",
    "hover:text-alphatauri",
    "hover:text-williams",
    "hover:border-mercedes",
    "hover:border-ferrari",
    "hover:border-red_bull",
    "hover:border-mclaren",
    "hover:border-aston_martin",
    "hover:border-alpine",
    "hover:border-alfa",
    "hover:border-haas",
    "hover:border-alphatauri",
    "hover:border-williams",
    "hover:shadow-mercedes/25",
    "hover:shadow-ferrari/25",
    "hover:shadow-red_bull/25",
    "hover:shadow-mclaren/25",
    "hover:shadow-aston_martin/25",
    "hover:shadow-alpine/25",
    "hover:shadow-alfa/25",
    "hover:shadow-haas/25",
    "hover:shadow-alphatauri/25",
    "hover:shadow-williams/25",
    "text-mercedes",
    "text-ferrari",
    "text-red_bull",
    "text-mclaren",
    "text-aston_martin",
    "text-alpine",
    "text-alfa",
    "text-haas",
    "text-alphatauri",
    "text-williams",
  ],
  theme: {
    extend: {
      fontFamily: {
        custom: "'F1 Font', serif",
      },
      colors: {
        primary: "#e10500",
        secondary: "#15141f",
        background: "#f6f5f2",
        mercedes: "#6CD3BF",
        ferrari: "#F91536",
        red_bull: "#3671C6",
        mclaren: "#F58020",
        aston_martin: "#358C75",
        alpine: "#2293D1",
        alfa: "#C92D4B",
        haas: "#B6BABD",
        alphatauri: "#2b4562",
        williams: "#37BEDD",
      },
    },
  },
  plugins: [],
}

